### ISSUE TITLE
Usage as a "normal" rofi plugin

### ISSUE THREAD

**Issue by teodorlu** [iterateno/iterbart-rofi#3]
Requested by @brynjagr 

As of now, `iterbart-rofi` is distributed as an executable Python script. This allows usage _only_ by binding a key to run a script.

Is it possible to distribute `iterbart-rofi` as a normal rofi plugin? This would integrate `iterbart-rofi` with [Rofi's combi mode][1].

[1]: https://github.com/davatorium/rofi#combi-mode

**Comment by teodorlu** [comment]
@teodorlu 's judgement:

I'm interested in achieving this. Script entry point was basically what I managed from a single day of work.

Anyone know how to create a rofi plugin with Python?

I've found examples using C, but I don't have a lot of experience with C.

**Comment by teodorlu** [comment]
Revisiting this. I'm not sure whether this addresses a real need.

1. Install is currently very simple. Just install curl, python and rofi, run the install script, done.
2. "proper rofi plugin" would couple us very tightly to rofi, and pull us away from other interfaces.

**Comment by teodorlu** [comment]
As of now, I'm not interested in tighter coupling to rofi. Python wrapper seems like an overall better option.

Closing.

**Comment by jraregris** [comment]
Er ikke `iterbart-rofi` allerede avhengig av `rofi`?

**Comment by teodorlu** [comment]
@jraregris tja. Per nå må du tilby en binary som heter `rofi` som oppfører seg som rofi. Jeg installerer ikke noen greier på systemet ditt.

Jeg har litt lyst til å støtte andre ting enn rofi. Men siden jeg bruker rofi, har jeg ikke hatt behovet ennå.

**Comment by jraregris** [comment]
https://github.com/iterate/iterbart-rofi#requirements
> iterbart-rofi requires python3, curl and rofi.
>
> On Ubuntu, try sudo apt install python3 curl rofi.
