### ISSUE TITLE
Keep links.json up to date

### ISSUE THREAD

**Issue by teodorlu** [iterateno/iterbart-rofi#6]
Currently, links.json must be kept up to date by the user, by manually re-running the `install` command. This shouldn't have to be the case.

I recently opened an outdated version of Simployer becase I didn't know Ole Martin had pushed changes & fixes. I'd like to fix this rather than working around.

**Comment by teodorlu** [comment]
Possible solution: download links every time.

Upsides:

1. Simple to implement
2. Up-to-date

Downsides:

1. Slow

**Comment by teodorlu** [comment]
Possible solution: trigger background job to update links.json, but finish very fast on the first run.

Upsides:

1. Low latency on every call
2. Frequent updates

Downsides:

1. I need to learn a bit about processes / threads in Python

Upsides:

1. I might want to learn a bit about background jobs in Python.

**Comment by teodorlu** [comment]
Possible solution: update links.json if links.json ... has not been updated since ... I don't know.

Somewhere in between the two above. Medium simplicity, medium speed. A bit messy.

**Comment by teodorlu** [comment]
Question: If I cache links.json, can I ask to get just an updated hash of links.json?

1. Is there an HTTP header I can use?
2. What HTTP headers are already provided? I think iterbart uses Nginx (on Iterapp)
3. I could also ask Ole Martin to provide a `links.json.md5sum`, and check that instead.

**Comment by teodorlu** [comment]
teod/decision: start by finding out which HTTP headers GET .../links.json gives me.

How do I do this with restclient.el?

**Comment by teodorlu** [comment]
```emacs-lisp
(defun restclient-parse-headers (string)
  (let ((start 0)
        (headers '()))
    (while (string-match restclient-header-regexp string start)
      (setq headers (cons (restclient-make-header string) headers)
            start (match-end 0)))
    headers))
```

**Comment by teodorlu** [comment]
teod/observasjon: det er ikke noen sjekksum i HTTP-response.

**Comment by teodorlu** [comment]
q: er det vanskelig å legge lage egen sjekksum?

**Comment by teodorlu** [comment]
Observasjon: Iterbart bruker rollup.js med svelte.

**Comment by teodorlu** [comment]
q: lager rollup.js noe manifest.json eller noe sånt? https://rollupjs.org/guide/en/

**Comment by teodorlu** [comment]
Dette funker i Node.js:

```javascript
> crypto.createHash("sha1", "something").digest("hex")
'da39a3ee5e6b4b0d3255bfef95601890afd80709'
```

Kilde: https://nodejs.org/api/crypto.html#crypto_crypto

**Comment by teodorlu** [comment]
Knowing myself, I should probably start simple: https://github.com/iterate/iterbart-rofi/issues/6#issuecomment-803296158

**Comment by teodorlu** [comment]
Simple solution done.

First impressions:

1. I'm not too annoyed by the added latency
2. It works

**Comment by teodorlu** [comment]
We DO have a cache header!

https://en.wikipedia.org/wiki/HTTP_ETag

```
teodorlu@T490s ~/dev/iterate/iterbart-rofi (git)-[master] % curl -D - https://iterbart.app.iterate.no/data/links.json
HTTP/1.1 200 OK
Server: openresty/1.15.8.2
Date: Sat, 20 Mar 2021 12:01:46 GMT
Content-Type: application/json
Content-Length: 2030
Connection: keep-alive
Vary: Accept-Encoding
Strict-Transport-Security: max-age=15724800; includeSubDomains
Last-Modified: Wed, 03 Mar 2021 19:15:45 GMT
ETag: "603fe061-7ee"
Accept-Ranges: bytes
```

**Comment by teodorlu** [comment]
How do I want to handle cache validation/invalidation?

**Comment by teodorlu** [comment]
1. I could save by etag and store latest etag
2. That could be triggered in the background and/or concurrently. Or ... just finish in sync afterwards?

```
$ ls ~/.local/share/iterbart-rofi/links.json/
~/.local/share/iterbart-rofi/links.json/603fe061-7ee
~/.local/share/iterbart-rofi/links.json/latest
$ cat ~/.local/share/iterbart-rofi/links.json/latest
603fe061-7ee
```

**Comment by teodorlu** [comment]
Nah, I'll leave caching for now. This is simple.

**Comment by jraregris** [comment]
Hva med å bruke `If-Modified-Since`?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since

**Comment by teodorlu** [comment]
Det kunne funka. Men det kommer ikke ut fra iterbart.app.iterate.no i dag.

ETag, derimot, ser ut til å være en form for innholdshash: ETag: "603fe061-7ee"
